#Oracle配置
#spring:
#  datasource:
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCLCDB
#    username: GUNS
#    password: GUNS
#    filters: wall,mergeStat

#SQLServer配置
#spring:
#  datasource:
#    driverClassName: net.sourceforge.jtds.jdbc.Driver
#    url: jdbc:jtds:sqlserver://127.0.0.1:3433;DatabaseName=guns
#    username: guns
#    password: 123456
#    filters: wall,mergeStat

#PostgreSQL配置
#spring:
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://127.0.0.1:5432/guns
#    username: postgres
#    password: 123456
#    filters: wall,mergeStat

# Mysql数据库
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    username: root
#    password: root
#    filters: wall,mergeStat

# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guns_advanced?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: EUrD9jIZtEQf8G9r
    filters: wall,mergeStat

    # 连接池大小根据实际情况调整
    max-active: 20
    max-pool-prepared-statement-per-connection-size: 20

  # 邮件发送配置（改为自己的账号和密码）
  mail:
    host: smtp.qq.com
    port: 587
    username: sn93@qq.com
    password: xxxpassword

# 邮件发送（改为自己的账号）
mail:
  from: sn93@qq.com

server:
  port: 9666
